### ISSUE TITLE
IdP metada url

### ISSUE THREAD

**Issue by cored** [calh/ruby-saml-rails3-example#4]
Hi @calh I was wondering where I can find the IdP metadata url, I'm trying with OneLogin. As far as I know you need to connect an app to it to get this working but they have a list of apps which doesn't include this one of course. Can you give me some guidance on this please? 

Thanks in advance,

**Comment by calh** [comment]
This app is a SAML Service Provider, not IdP.  If you need help using OneLogin, read their documents or contact their support.

**Comment by cored** [comment]
@calh got it; thanks
