### ISSUE TITLE
how to generate .crt and .pem file 

### ISSUE THREAD

**Issue by chetanbissa27** [calh/ruby-saml-rails3-example#5]
I am setting certificate and private_key on local to generate metadata.Please let me know how to generate that.

**Comment by calh** [comment]
[This is the metadata method in the SAML controller](https://github.com/calh/ruby-saml-rails3-example/blob/master/app/controllers/saml_controller.rb#L161).  By default, that controller is hooked up to the `/saml/` path, so your metadata will be rendered from the path `/saml/metadata`
